name: ddamsproteomics-1.2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::msgf_plus=2019.07.03
  - bioconda::hardklor=2.3.0
  - bioconda::kronik=2.20
  - bioconda::msstitch=2.17
  - conda-forge::biopython=1.72
  - bioconda::percolator=3.1
  - conda-forge::lxml=4.2.5
  - conda-forge::jinja2=2.10
  - conda-forge::r-argparse=2.0.1
  - conda-forge::r-ggplot2=3.0.0
  - conda-forge::r-ggrepel=0.8.1
  - conda-forge::r-reshape2=1.4.3
  - conda-forge::r-forcats=0.3.0
  - conda-forge::r-rmarkdown=1.10
  - conda-forge::r-matrixstats=0.54.0
  - bioconda::bioconductor-deqms=1.0.1
