name: nf-core-ddamsproteomics-1.0.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::msgf_plus=2017.07.21
  - bioconda::hardklor=2.3.0
  - bioconda::kronik=2.20
  - bioconda::msstitch=2.9
  - conda-forge::biopython=1.72
  - bioconda::percolator=3.1
  - conda-forge::lxml=4.2.5
  - conda-forge::jinja2=2.10
  - conda-forge::r-ggplot2=3.0.0
  - conda-forge::r-reshape2=1.4.2
  - conda-forge::r-forcats=0.3.0
  - conda-forge::r-rmarkdown=1.10
